tls:
  server: 
    keystore:
      type: "JKS"
      fileName: "keyStores/nonprod-keystore.jks"
      alias: "mule"
      keyPassword: "![81i+q1l/rbHe6Lo9lmXe7XjGl1Si0MT7sdb82wpOCeg=]"
      password: "![81i+q1l/rbHe6Lo9lmXe7XjGl1Si0MT7sdb82wpOCeg=]"
  

http:
  system1:
    host: "localhost"
    port: "8082"
    maxConnections: "-1"
    timeout: "30000"
    client_id: ""
    client_secret: ""
    reconnect:
      frequency: "3000"
      attempts: "2"
    path:
      base: "/api"
      integrationStatus: "/integrations/status"
      ping: "/ping"
      composite: "/composite"