tls:
  server: 
    truststore:
      fileName: "trustStores/truststore.p12"
      password: "123"
      type: "PKCS12"
    keystore:
      type: "PKCS12"
      fileName: "keyStores/server.p12"
      alias: "server"
      keyPassword: "456"
      password: "123"
  
  client:
    truststore:
      fileName: "trustStores/truststore.p12"
      password: "123"
      type: "PKCS12"
    keystore:
      type: "PKCS12"
      fileName: "keyStores/client.p12"
      alias: "client"
      keyPassword: "456"
      password: "123"

sapi:
  salesforce:
    host: "localhost"
    port: "8092"
    maxConnections: "-1"
    timeout: "30000"
    client_id: ""
    client_secret: ""
    reconnect:
      frequency: "3000"
      attempts: "2"
    path:
      base: "/api"
      integrationStatus: "/integration/status"
      contacts: "/contacts"
      ping: "/ping"
      composite: "/composite"