tls:
  server: 
    keystore:
      type: "PKCS12"
      fileName: "keyStores/server.p12"
      alias: "server"
      keyPassword: "456"
      password: "123"
  

sapi:
  salesforce:
    host: "localhost"
    port: "8082"
    maxConnections: "-1"
    timeout: "30000"
    client_id: ""
    client_secret: ""
    reconnect:
      frequency: "3000"
      attempts: "2"
    path:
      base: "/api"
      integrationStatus: "/integrations/status"
      ping: "/ping"
      composite: "/composite"